networks:
  mastercrm-dev:
    driver: bridge
services:
  mastercrm.api:
    container_name: mastercrm.api
    image: mastercrm.api
    build:
      context: .
      dockerfile: src/MasterCRM.Api/Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      DB_CONTAINER: "mastercrm.db"
  mastercrm.db:
    container_name: mastercrm.db
    image: postgres:latest
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data: